spring:
  application:
    name: saju_back
  datasource:
    url: jdbc:postgresql://localhost:5432/saju
    username: postgres
    password: admin
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: 8081

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.saju.domain

kakao:
  client-id: 1186384fe0d59f94ea12f49b56cf8151
  client-secret: fWGlmhXvIJFM5HZWMSJtP7CzMqQfniA6
  redirect-uri: http://localhost:5173/oauth/kakao/callback

jwt:
  secret: 8f3a9b2c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b
  expire-ms: 3600000
